### ISSUE TITLE
IndexedDB Observer / Event protocol

### ISSUE THREAD

**Issue by bahrus** [webcomponents/community-protocols#9]
I think the [IndexedDB Observers](https://www.chromestatus.com/feature/5669292892749824) proposal seems quite useful.  I think it would provide a strong basis for a common state management, at least for some aspects of state, when required.  Sharing state across iframes / windows tabs could also be quite elegant, more so than using postMessage.  See [this discussion](https://youtu.be/9UNwHmagedE?t=789) for more details.

Unfortunately, the proposal seems to be stalled, even within Chrome, and doesn't seem to have attracted attention from other browser vendors.

My (not very confident) guess is that "polyfilling" the IndexedDB Observers proposal would be quite difficult, as it requires intercepting a number of native calls.

But let's imagine that everyone using web components used the same library from userland whenever they  stored something in IndexedDB.  I suspect using the raw IndexedDB api's is rather rare, and that most access to IndexedDB is done via a library, such as localForage or idb-keyval.  Would it not be possible to add an observer api on top of each of these  common libraries?

I'm not a big fan of trying to promote that everyone use the same library.  I'm thinking it might be possible to add some subscription type functionality on top of any indexedDB library, starting with localForage and idb-keyval, but make that publish/subscribe functionality conform to a common api, which would make cross-component state management based on indexedDB possible, even across components that utilize different libraries

I don't know the api's well enough to know if this is possible, but I'm first wondering how much interest there would be in something like this?  And does this seem feasible?

**Comment by justinfagnani** [comment]
I would love to see IndexedDB Observers move forward! I agree that this isn't polyfillable outside of some collaboration between all clients of the same db, but I don't think it relates much to web components or UI components in general. Seems like something that should be implemented with a reference/prototype implementation first, and then have a protocol derived from that.

I'm going to close this as out-of-scope for web components protocols though.
